spring:
  profiles:
    active: dev

  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/zoom
      username: zoom
      password: zoom
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: test
      password: test
      driver-class-name: com.mysql.cj.jdbc.Driver


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
  file:
    name: ./logs/tools.log
