spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/zoom
    username: zoom
    password: zoom
    driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      url: jdbc:mysql://localhost:3306/test
      username: test
      password: test
      driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
  file:
    name: ./logs/tools.log

management:
  endpoints:
    web:
      exposure:
        include: "*"


